### ISSUE TITLE
sorting heatmaps

### ISSUE THREAD

**Issue by aaubry89** [andymckenzie/DGCA#4]
Hi, I have a question about the sortby option in the ddcorall function. The manual only gives "zScoreDiff" as an option. I'd like to leave the order of the genes as they are in the original matrix. Is this a possible option? What would be the character string? thanks.

**Comment by andymckenzie** [comment]
Hello and thanks for using DGCA. 

It is a bit difficult to leave the order of the genes as in the original matrix because the ddcorAll() function returns an object that has pairs of genes per row rather than one gene per row.  So you would need to sort the df by the values of multiple columns. 

To be more specific, what the ddcorAll() function is doing to sort is: 

`ddcor_table[order(-abs(ddcor_table[ , sortBy])), ]
`

As you can see, this is not conducive to sorting by multiple columns of the data frame. So, unfortunately, what you are requesting is not supported by DGCA. 

Rather than using the sortby option in the ddcorAll() function, which would sort by a single column, I'd recommend doing this sorting in the resulting data frame so that you can sort by both the Gene1 and Gene2 columns. You will also want to set nPairs = "all" in ddcorAll() so that it doesn't filter by the top results based on zScoreDiff. If you're having trouble with this and can post a minimal reproducible example, I can try to help you with it.

**Comment by aaubry89** [comment]
Thanks so much for your quick response. if I have any trouble I will post an example in the near future.

**Comment by andymckenzie** [comment]
Great. Please feel free to re-open the issue or another one at that time.
