### ISSUE TITLE
Differential significance across differential correlation classes?

### ISSUE THREAD

**Issue by RegnerM2015** [andymckenzie/DGCA#9]
Hi @andymckenzie,

Thank you for developing this amazing resource!

I am working on translating DGCA to a similar use case, but instead correlating the expression of genes, I am computing correlations between gene expression and peak accessibility (as measured by open chromatin profiling techniques such as ATAC-seq). So far, my results look promising. 

However, I have noticed that the "+/-" and "-/+" differential correlation classes typically have higher differential correlation Z scores and are typically "more statistically significant" relative to the other differential correlation classes:

<img width="833" alt="Screen Shot 2023-01-24 at 4 15 52 PM" src="https://user-images.githubusercontent.com/54336249/214418299-881d17b2-0cf3-4713-830e-ba66269f50b4.png">
<img width="833" alt="Screen Shot 2023-01-24 at 4 16 21 PM" src="https://user-images.githubusercontent.com/54336249/214418301-9e8c03c3-fff3-4f41-a040-e3182d4fe273.png">

```
classes <- dCorClass(corsB = p2g.2$Correlation,
                           corsA = p2g.1$Correlation,
                           pvalsB = p2g.2$FDR,
                           pvalsA = p2g.1$FDR,
                           dCorPVals = pvals_res_adj,
                           sigThresh = 1e-2,
                           corSigThresh = 1e-2,
                           convertClasses = T)
```
Based on my interpretation of my code above, I used 0.01 as the threshold for calling the correlation in each condition statistically significant and as the threshold for calling a differential correlation. Based on how a peak-gene pair passes these thresholds, it is sorted into one of the nine differential correlation classes or is labeled "NonSig" if the differential correlation test FDR p-value >0.01. 

My interpretation of the "+/-" and "-/+" differential correlation classes typically having higher differential correlation Z scores and lower p-values, is that this may arise naturally due to the natural difference in magnitude in a "+/-" or "-/+" scenario relative to a "+/0" or "-/0" scenario. In other words, having a positive correlation in condition A with a negative correlation in condition B would more often lead to large differential correlation Z scores simply b/c they are on both sides of 0. Whereas the "+/0" scenario would require a more drastic difference in Z score to achieve similar values to those observed in "+/-" or "-/+". 

Please feel free to provide feedback or correct any misunderstandings that I may have. If you could suggest some ideas or changes to my analysis, that would be greatly appreciated!

**Comment by andymckenzie** [comment]
Hi RegnerM2015,

Thank you for using DGCA! Thanks as well for your observations regarding the "+/-" and "-/+" differential correlation classes. It sounds like you have a good understanding of the code and the results that you are seeing. 

I think that your interpretation of the results is correct. The "+/-" and "-/+" classes typically have higher differential correlation Z scores and lower p-values because the magnitude of the difference between the two correlations is greater than in the "+/0" or "-/0" scenarios. 

I can't think of any suggestions for changes to your analysis. It probably depends on precisely what your goals are, which might be beyond the scope of just a discussion of the software per se. 

I hope this is helpful and best of luck with your research.

**Comment by RegnerM2015** [comment]
Thanks @andymckenzie!

I reached out on LinkedIn to hopefully continue our discussion.
